object Form1: TForm1
  Left = 40
  Top = 0
  Caption = 'Form1'
  ClientHeight = 825
  ClientWidth = 1272
  Color = clBtnFace
  Constraints.MinHeight = 768
  Constraints.MinWidth = 1272
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
